export default {
    'variable': 'let',
    'constante': 'const',
    'nulo': 'null',
    'indefinido': 'undefined',
    'y': '&&',
    'o': '||',
    'no': '!',
    'igual': '==',
    'estrictamente_igual': '===',
    'diferente': '!=',
    'estrictamente_diferente': '!==',
    'mayor_que': '>',
    'menor_que': '<',
    'mayor_o_igual_que': '>=',
    'menor_o_igual_que': '<=',
    'asignar': '=',
    'si': 'if',
    'sino': 'else',
    'para': 'for',
    'mientras': 'while',
    'hacer': 'do',
    'interrumpir': 'break',
    'continuar': 'continue',
    'funcion': 'function',
    'retornar': 'return',
};